### ISSUE TITLE
issue on start the project

### ISSUE THREAD

**Issue by slider973** [danyRafina/iumio-framework#1]
Hy I have a problème went i start the project i dont know how to start my project after use the command  php bin/manager app create 
how to start my projet i have to use a webserver like mamp or i have to use a command but which ?

**Comment by danyRafina** [comment]
Hi, thanks you for using iumio Framework.
Please follow instructions on this link.
https://framework.iumio.com/installation/manual

If you have an other problem, please contact me by email (danyrafina+iumio@gmail.com) for more information.
